project_name: devopsdays-cli
release:
  github:
    owner: devopsdays
    name: devopsdays-cli
# brew:
#   install: bin.install "devopsdays-cli"
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - 386
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X github.com/devopsdays/devopsdays-cli/cmd.Version={{.Version}} -X github.com/devopsdays/devopsdays-cli/cmd.Build={{.Date}}
  binary: devopsdays-cli
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  files:
  - LICENSE*
  - README*
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
