engines:
  gofmt:
    enabled: true
  golint:
    enabled: true
  govet:
    enabled: true
  fixme:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
- testdata
- vendor
- .version.sh
