dist: trusty
sudo: no
language: go
addons:
  apt:
    packages:
    - rpm
go: 1.9

before_install:
  - go get github.com/mattn/goveralls
  - export DODPATH=$HOME/gopath/src/github.com/devopsdays/devopsdays-cli/sampleData
install:
  - make install
script: go test ./...
before_deploy:
  - go get -v github.com/inconshreveable/mousetrap
  - gem install fpm
  - which fpm
deploy:
  skip_cleanup: true
  provider: script
  script: curl -sL https://git.io/goreleaser | rvm 2.4.1 do bash
  on:
    tags: true
notifications:
  email: false
