language: go
sudo: false
go:
  - 1.8

before_install:
  - go get github.com/mattn/goveralls

install:
  - make install

before_deploy:
  - go get -v github.com/inconshreveable/mousetrap

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
