dist: trusty
sudo: required
language: go
go: 1.9
services:
  - docker
before_install:
  - go get github.com/mattn/goveralls
  - export DODPATH=$HOME/gopath/src/github.com/devopsdays/devopsdays-cli/sampleData
install:
  - make install
script: go test ./...
before_deploy:
  - go get -v github.com/inconshreveable/mousetrap
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - gem install fpm
  - which fpm
  - sudo apt-get update
  - sudo apt-get install --yes snapd rpm
  - export PATH=/snap/bin:$PATH
  - which snap
  - sudo snap install snapcraft --candidate --classic
deploy:
  skip_cleanup: true
  provider: script
  script: curl -sL https://git.io/goreleaser | rvm 2.4.1 do bash
  on:
    tags: true
notifications:
  email: false
