language: go
sudo: false
go:
  - 1.8

before_install:
  - go get github.com/mattn/goveralls

install:
  - make install

before_deploy:
  - go get -v github.com/inconshreveable/mousetrap
  - gem install fpm
  - which fpm
  - export PATH=$HOME/.rvm/gems/ruby-2.4.1/bin:$PATH
  - echo $PATH
  - ls $HOME/.rvm/gems/ruby-2.4.1/bin/

deploy:
  - provider: script
    skip_cleanup: true
    script: rvm use 2.4.1 do curl -sL http://git.io/goreleaser | bash
    on:
      tags: true
