version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

skip_tags: true # Just for now because of looping!
clone_folder: c:\gopath\src\github.com\devopsdays\devopsdays-cli

environment:
  GOPATH: c:\gopath

install:
- echo %PATH%
- echo %GOPATH%
- set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
- go version
- go env
- go get -t -v ./...

build_script:
  - go build -o buildOutput\devopsdays-cli -i .

artifacts:
  - path: buildOutput/devopsdays-cli
    name: binary

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'This is a release of my awesome application.'
  provider: GitHub
  auth_token:
    secure: iNVocPf2TIAUFwOG5txOr4blIMmAOI+iI/yJulYPoYJOxucpdpEmPX/uuBz7rDPu
  artifact: binary # This is the name we specified in the artifacts section.
  draft: false
  prerelease: true
  on:
    branch: master
    appveyor_repo_tag: true
